---
baseurl: "https://nemoworld.info/"
languageCode: "en-us"
title: "Nemoworld"

pluralizeListTitles: true

permalinks:
    blog: /blog/:year/:month/:day/:slug/
    archive: /oldblog/:year/:month/:day/:slug/
    project: /project/:slug

metaDataFormat: "yaml"

pygmentsuseclasses: false
pygmentsstyle: perldoc

taxonomies:
    topic: topics

disableKinds:
  - RSS

menu:
    main:
        - Name: "Blog"
          Weight: -110
          Identifier: "blog"
          URL: "/blog/"
        - Name: "Projects"
          Weight: -100
          Identifier: "project"
          URL: "/project/"
        - Name: "Notes"
          Weight: -90
          Identifier: "note"
          URL: "/note/"
        - Name: "Recipes"
          Weight: -85
          Identifier: "recipe"
          URL: "/recipe/"
        - Name: "About"
          Weight: -80
          Identifier: "about"
          URL: "/about/"
---
