---
baseurl: "http://nemoworld.info/"
languageCode: "en-us"
title: "Nemo~world"

pluralizeListTitles: false

permalinks:
    blog: /blog/:year/:month/:day/:title/
    project: /project/:title

metaDataFormat: "yaml"

theme: "nemo2016"

pygmentsuseclasses: false
pygmentsstyle: pastie

taxonomies:
    topic: topics

menu:
    main:
        - Name: "Blog"
          Pre: "<i class='fa fa-heart'></i>"
          Weight: -110
          Identifier: "blog"
          URL: "/blog/"
        - Name: "Project"
          Pre: "<i class='fa fa-heart'></i>"
          Weight: -100
          Identifier: "project"
          URL: "/project/"
        - Name: "Note"
          Pre: "<i class='fa fa-heart'></i>"
          Weight: -90
          Identifier: "note"
          URL: "/note/"
        - Name: "About"
          Pre: "<i class='fa fa-heart'></i>"
          Weight: -80
          Identifier: "about"
          URL: "/about/"
---