baseURL = "https://nemoworld.info"
languageCode = "en-us"
title = "Nemoworld"
theme = "2022"

assetDir = "static"

[permalinks]
  posts = "posts/:year/:month/:day/:slug/"
  archive = "/oldblog/:year/:month/:day/:slug/"
 

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "manni"
    tabWidth = 4

[menu]
  [[menu.nav]]
    name = "Blog"
    url = "/posts/"
    weight = 1
  [[menu.nav]]
    name = "Projects"
    url = "/projects/"
    weight = 2
  [[menu.nav]]
    name = "Notes"
    url = "/notes/"
    weight = 3
  [[menu.nav]]
    name = "Recipes"
    url = "/recipes/"
    weight = 4
  [[menu.nav]]
    name = "Drawings"
    url = "/drawings"
    weight = 5
  [[menu.nav]]
    name = "Contact"
    url = "/contact"
    weight = 20

[taxonomies]
  topic = "topics"
