baseURL = "https://www.nemoworld.info"
languageCode = "en-us"
title = "Nemoworld"
theme = "2022"

assetDir = "static"

# To actually ignore issues with the shortcode "youtube"
ignoreLogs = ['err-youtube-remote']

[permalinks]
  posts = "posts/:year/:month/:day/:slug/"
  archive = "/oldblog/:year/:month/:day/:slug/"
 

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

[menu]
  [[menu.nav]]
    name = "Blog"
    url = "/posts/"
    weight = 10
  [[menu.nav]]
    name = "Projects"
    url = "/projects/"
    weight = 20
  [[menu.nav]]
    name = "Notes"
    url = "/notes/"
    weight = 60
  [[menu.nav]]
    name = "Recipes"
    url = "/recipes/"
    weight = 50
  [[menu.nav]]
    name = "Drawings"
    url = "/drawings"
    weight = 40
  [[menu.nav]]
    name = "Astronomy"
    url = "/astronomy"
    weight = 30
  [[menu.nav]]
    name = "Contact"
    url = "/contact"
    weight = 100

[taxonomies]
  topic = "topics"
